name: Tact CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Build and Test Tact compiler
      run: |
        yarn install
        yarn clean
        yarn build
        yarn gen
        yarn coverage

    - name: Test with Tact Template
      run: |
        git clone https://github.com/tact-lang/tact-template.git
        cd tact-template && yarn install && yarn build && yarn test
