name: Claude Auto Review

on:
  pull_request

jobs:
  auto-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate review with Claude
        id: claude
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt_file: ".github/PROMPTS/review.txt"
          allowed_tools: "View,GlobTool,GrepTool,Bash(git diff HEAD~1)"  # keep it simple
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Post review
        if: steps.claude.outputs.conclusion == 'success'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const log = JSON.parse(fs.readFileSync(process.env.REVIEW_LOG, 'utf8'));
            const reviewBody = log.findLast(m => m.role === 'assistant').content;
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'COMMENT',
              body: reviewBody
            });
        env:
          REVIEW_LOG: ${{ steps.claude.outputs.execution_file }}
