name: Claude Auto Review

on:
  pull_request

jobs:
  auto-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate review with Claude
        id: code-review
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt_file: ".github/PROMPTS/review.txt"
          allowed_tools: "View,GlobTool,GrepTool,Bash"  # keep it simple
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Post PR review
        if: steps.code-review.outputs.conclusion == 'success'
        uses: actions/github-script@v7
        env:
          EXEC_FILE: ${{ steps.code-review.outputs.execution_file }}
        with:
          script: |
            const fs   = require('fs');
            const log  = JSON.parse(fs.readFileSync(process.env.EXEC_FILE,'utf8'));

            // last assistant message that actually contains text
            const assistant = [...log].reverse()
              .find(m => m.role === 'assistant' && m.content?.length);

            if (!assistant)
              throw new Error('No assistant message found in execution log');

            const body = assistant.content
              .filter(p => p.type === 'text')
              .map(p => p.text.trim())
              .join('\n\n');

            if (!body)
              throw new Error('Assistant message had no text parts');

            const res = await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              pull_number: context.issue.number,
              event: 'COMMENT',    // or 'APPROVE' / 'REQUEST_CHANGES'
              body
            });

            core.info(`✅  review #${res.data.id} posted`);
