name: Claude Auto Review

on:
  pull_request

jobs:
  auto-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Automatic PR Review
        uses: anthropics/claude-code-base-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          mcp_config: ".github/MCP/mcp-config.json"
          allowed_tools: "mcp__github__create_pull_request_review,mcp__github__add_pull_request_review_comment"
          prompt_file: ".github/PROMPTS/review.txt"