name: Claude Auto Review

on:
  pull_request

jobs:
  auto-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate review with Claude
        id: code-review
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt_file: ".github/PROMPTS/review.txt"
          allowed_tools: "View,GlobTool,GrepTool,Bash"  # keep it simple
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Post PR review
        if: steps.code-review.outputs.conclusion == 'success'
        uses: actions/github-script@v7
        env:
          REVIEW_BODY: ${{ steps.code-review.outputs.result }}
        with:
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              pull_number: context.issue.number,
              event: 'COMMENT',          // or 'APPROVE'
              body: process.env.REVIEW_BODY
            });
