name: Claude Auto Review

on:
  pull_request

jobs:
  auto-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate review with Claude
        id: code-review
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt_file: ".github/PROMPTS/review.txt"
          allowed_tools: "View,GlobTool,GrepTool,Bash"  # keep it simple
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Extract and Comment PR Review
        if: steps.code-review.outputs.conclusion == 'success'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const executionFile = '${{ steps.code-review.outputs.execution_file }}';
            const executionLog = JSON.parse(fs.readFileSync(executionFile, 'utf8'));

            // Extract the review content from the execution log
            // The execution log contains the full conversation including Claude's responses
            let review = '';

            // Find the last assistant message which should contain the review
            for (let i = executionLog.length - 1; i >= 0; i--) {
              if (executionLog[i].role === 'assistant') {
                review = executionLog[i].content;
                break;
              }
            }

            const res = await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              pull_number: context.issue.number,
              event: 'COMMENT',    // or 'APPROVE' / 'REQUEST_CHANGES'
              body: review
            });

            core.info(`✅  review #${res.data.id} posted`);
